/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/root/flex/flex/skel.c,v 1.2 2004/05/07 00:28:17 jkh Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[552] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  115,  113,
      111,  110,    4,    6,  113,  106,    3,  113,    1,    1,
      108,  107,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  109,   17,   18,   10,  114,  114,    7,    8,  111,
        0,    3,    1,    3,    9,    2,    0,    0,    0,    0,
        0,    0,    0,    0,  112,    0,    0,    0,    0,    0,
        0,    0,    0,   40,   89,    0,    0,    0,    0,    0,
        0,  104,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   17,   16,   14,   15,   11,   13,
       12,    2,    5,    0,    0,    0,    0,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   41,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   53,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   92,
        0,    0,    0,    0,    0,    0,    0,    0,   72,    0,
        0,  105,    0,    0,    0,    0,    0,   26,    0,    0,
        0,    0,    0,    0,    0,   29,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   46,   84,

       47,    0,    0,    0,   55,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   93,    0,    0,    0,    0,
       66,    0,    0,    0,    0,    0,   71,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   85,    0,    0,    0,    0,   38,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   51,   52,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   59,
        0,    0,    0,    0,   91,    0,   64,    0,   67,    0,
        0,    0,    0,    0,   94,    0,   20,    0,   23,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   35,    0,

       37,    0,    0,    0,    0,   44,    0,    0,    0,    0,
        0,    0,   56,    0,    0,    0,    0,    0,    0,   90,
        0,   60,    0,    0,    0,    0,    0,   65,    0,   68,
        0,    0,   73,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   96,   95,    0,    0,    0,
        0,    0,    0,    0,   74,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   39,   42,    0,    0,    0,    0,    0,    0,   54,

        0,    0,    0,    0,    0,   81,    0,    0,    0,   87,
        0,    0,    0,   69,    0,   98,   97,    0,    0,    0,
       22,   86,   27,   78,    0,    0,   88,    0,    0,    0,
        0,    0,    0,    0,   48,   49,   50,    0,   80,    0,
       79,   82,    0,    0,    0,    0,   75,    0,    0,  101,
        0,    0,  102,    0,    0,    0,    0,   33,    0,    0,
        0,    0,    0,  103,   83,   57,    0,    0,    0,    0,
       77,    0,    0,    0,   76,    0,    0,    0,    0,  100,
       99,    0,    0,    0,   61,   62,   63,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   21,    0,    0,    0,   32,    0,    0,    0,    0,
       70,    0,    0,    0,    0,    0,   43,   45,    0,    0,
       28,   30,    0,    0,    0,    0,    0,    0,    0,    0,
       31,    0,   58,    0,    0,    0,    0,    0,   36,   19,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    7,    9,   10,   11,   12,   13,
       14,   14,   15,   14,   14,   14,   16,   17,   18,    1,
       19,    1,    1,    1,   20,   20,   20,   20,   20,   20,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   21,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,    1,   39,   40,   41,   42,   43,   44,   45,
       46,   47,    1,    1,    1,   48,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    3,    1,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    5,
        2,    1,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[559] =
    {   0,
        0,    0,   46,   48,    0,    0,  625,  624,  626,  629,
      623,  629,  629,  629,   46,  629,   45,  618,   55,   59,
      629,  629,   20,   42,   60,  596,   53,  588,  598,   57,
      579,  582,   70,   44,   73,   82,   89,   60,   90,  579,
      590,  629,    0,  629,  629,   95,  629,  629,  629,  614,
       78,  126,  134,  140,  629,  146,    0,  581,  575,   62,
      576,  599,   38,  570,  629,  579,  583,  137,   86,  585,
      568,  583,  565,  565,  629,  580,  579,  556,  565,   63,
      138,  629,  564,   93,  563,  132,  142,  570,  557,  560,
      548,  144,  560,  553,  544,  555,  150,  553,  553,  549,

      561,  539,  553,  543,    0,  629,  629,  629,  629,  629,
      629,  175,    0,  545,  565,  547,  553,  553,  629,  549,
      535,  548,  536,  546,  541,  548,  547,  544,  537,  528,
      527,  541,  530,  523,  540,  629,  532,  534,  537,  521,
      535,  519,  528,  523,  531,  525,  103,   99,  517,  509,
      523,  519,  505,  509,  507,  510,  517,  515,  502,  629,
      144,  513,  514,  514,  522,  511,  508,  507,  629,  499,
      491,  629,  487,  518,  154,  490,  495,  629,  500,  500,
      503,  479,  498,  480,  475,  629,  495,  629,  482,  484,
      490,  486,  483,  479,  475,  468,  472,  466,  629,  629,

      629,  158,  171,  475,  629,  481,  480,  163,  480,  478,
      465,  477,  474,  454,  473,  177,  458,  452,  473,  473,
      629,  456,  468,  482,  462,  454,  629,  463,  462,  460,
      476,  446,  459,  461,  443,  443,  454,  453,  452,  455,
      443,  629,  449,  440,  447,  447,  629,  431,  438,  447,
      430,  422,  428,  443,  442,  424,  629,  629,  429,  426,
      435,  424,  432,  435,  430,  422,  432,  417,  425,  629,
      426,   95,  428,  419,  629,  427,  629,  414,  629,  420,
      435,  411,  402,  417,  170,  400,  419,  409,  629,  398,
      407,  409,  402,  396,  408,  392,  391,  406,  629,  392,

      629,  406,  397,  398,  395,  629,  394,  388,  394,  391,
      394,  397,  629,  393,  377,  383,  382,  392,  379,  629,
      391,  629,  381,  374,  385,  362,  370,  629,  373,  152,
      369,  364,  629,  170,  381,  369,  376,  354,  373,  352,
      364,  374,  373,  368,  367,  371,  355,  368,  361,  358,
      361,  346,  345,  352,  357,  336,  348,  357,  353,  349,
      336,  354,  330,  340,  351,  629,  629,  340,  345,  329,
      347,  343,  355,  330,  629,  335,  328,  335,  329,  335,
      334,  629,  333,  313,  312,  317,  322,  329,  169,  328,
      324,  629,  629,  330,  324,  323,  309,  308,  320,  629,

      312,  300,  307,  316,  296,  629,  314,  312,  317,  629,
      304,  291,  309,  629,  297,  629,  629,  307,  295,  289,
      629,  629,  629,  629,  304,  307,  629,  179,  302,  301,
      300,  180,  304,  303,  629,  629,  629,  297,  629,  297,
      629,  629,  283,  280,  282,  279,  629,  275,  277,  629,
      293,  290,  292,  267,  273,  274,  271,  629,  271,  277,
      270,  280,  279,  629,  629,  629,  277,  199,  276,  277,
      629,  272,  263,  273,  629,  275,  268,  265,  256,  629,
      629,  267,  266,  253,  629,  629,  629,  254,  263,  263,
      261,  253,  247,  262,  247,  249,  248,  259,  254,  255,

      251,  243,  242,  252,  240,  244,  249,  248,  226,  242,
      237,  629,  244,  239,  230,  629,  225,  217,  216,  222,
      629,  219,  213,  224,  222,  233,  629,  629,  224,  214,
      629,  629,  226,  217,  210,  209,  210,  213,  210,  177,
      629,  184,  629,  186,  167,  147,   99,   43,  629,  629,
      629,  218,  223,  228,  231,  235,  240,  242
    } ;

static yyconst short int yy_def[559] =
    {   0,
      551,    1,  552,  552,  553,  553,  554,  554,  551,  551,
      551,  551,  551,  551,  555,  551,  551,  551,  555,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  556,  551,  551,  557,  551,  551,  551,  551,
      555,  551,  551,  551,  551,  551,  558,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  556,  551,  551,  551,  551,  551,
      551,  551,  558,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
        0,  551,  551,  551,  551,  551,  551,  551
    } ;

static yyconst short int yy_nxt[678] =
    {   0,
       10,   11,   12,   13,   14,   10,   15,   16,   17,   18,
       19,   20,   20,   20,   20,   20,   10,   21,   22,   10,
       10,   10,   23,   24,   25,   26,   27,   28,   10,   29,
       30,   31,   10,   32,   33,   34,   10,   35,   36,   37,
       38,   10,   39,   40,   10,   41,   10,   42,   44,   45,
       44,   45,   51,   58,   52,   54,   54,   54,   54,   54,
       54,  551,   59,   56,   60,  120,   46,   56,   46,   53,
       53,   53,   53,   53,   53,   61,   65,  550,  121,   69,
       82,   62,   74,   63,   51,   83,   52,   64,   70,   66,
       99,   71,   78,   75,   67,   84,   79,  116,  141,   57,

       80,   85,  142,  117,   90,  100,   81,   91,   92,   86,
      130,   87,   88,   93,  101,   94,   89,  102,  107,   95,
      206,  146,  108,  131,  323,  204,   96,  549,  324,   97,
      109,  147,  207,  110,   98,  111,   54,   54,   54,   54,
       54,   54,   56,  205,   53,   53,   53,   53,   53,   53,
       54,   54,   54,   54,   54,   54,  112,  112,  112,  112,
      112,  112,  125,  143,  126,  149,  157,  219,  151,  548,
      127,  150,  164,  372,  220,  232,  128,  144,  152,  129,
      233,  254,  165,  158,  159,  112,  112,  112,  112,  112,
      112,  334,  256,  262,  373,  255,  257,  263,  272,  376,

      273,  455,  547,  377,  258,  264,  428,  335,  429,  460,
      485,  486,  546,  461,  545,  544,  274,  456,   43,   43,
       43,   43,   43,   47,   47,   47,   47,   47,   48,   48,
       48,   48,   48,   53,   53,  105,  543,  105,  105,  105,
      106,  106,  106,  106,  106,  113,  113,  542,  541,  540,
      539,  538,  537,  536,  535,  534,  533,  532,  531,  530,
      529,  528,  527,  526,  525,  524,  523,  522,  521,  520,
      519,  518,  517,  516,  515,  514,  513,  512,  511,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,

      489,  488,  487,  484,  483,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  459,  458,  457,  454,
      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,
      391,  390,  389,  388,  387,  386,  385,  384,  383,  382,

      381,  380,  379,  378,  375,  374,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  271,

      270,  269,  268,  267,  266,  265,  261,  260,  259,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  163,
      162,  161,  160,  156,  155,  154,  153,  148,  145,  140,

      139,  138,  137,  136,  135,  134,  133,  132,  124,  123,
      122,  119,  118,  115,  114,   50,  104,  103,   77,   76,
       73,   72,   68,   55,   50,  551,   49,   49,    9,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551
    } ;

static yyconst short int yy_chk[678] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,   15,   23,   15,   17,   17,   17,   17,   17,
       17,   19,   23,   19,   24,   63,    3,   20,    4,   20,
       20,   20,   20,   20,   20,   24,   25,  548,   63,   27,
       34,   24,   30,   24,   51,   34,   51,   24,   27,   25,
       38,   27,   33,   30,   25,   35,   33,   60,   80,   19,

       33,   35,   80,   60,   36,   38,   33,   36,   36,   35,
       69,   35,   35,   37,   39,   37,   35,   39,   46,   37,
      148,   84,   46,   69,  272,  147,   37,  547,  272,   37,
       46,   84,  148,   46,   37,   46,   52,   52,   52,   52,
       52,   52,   53,  147,   53,   53,   53,   53,   53,   53,
       54,   54,   54,   54,   54,   54,   56,   56,   56,   56,
       56,   56,   68,   81,   68,   86,   92,  161,   87,  546,
       68,   86,   97,  330,  161,  175,   68,   81,   87,   68,
      175,  202,   97,   92,   92,  112,  112,  112,  112,  112,
      112,  285,  203,  208,  330,  202,  203,  208,  216,  334,

      216,  428,  545,  334,  203,  208,  389,  285,  389,  432,
      468,  468,  544,  432,  542,  540,  216,  428,  552,  552,
      552,  552,  552,  553,  553,  553,  553,  553,  554,  554,
      554,  554,  554,  555,  555,  556,  539,  556,  556,  556,
      557,  557,  557,  557,  557,  558,  558,  538,  537,  536,
      535,  534,  533,  530,  529,  526,  525,  524,  523,  522,
      520,  519,  518,  517,  515,  514,  513,  511,  510,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  484,  483,  482,  479,  478,  477,  476,  474,  473,

      472,  470,  469,  467,  463,  462,  461,  460,  459,  457,
      456,  455,  454,  453,  452,  451,  449,  448,  446,  445,
      444,  443,  440,  438,  434,  433,  431,  430,  429,  426,
      425,  420,  419,  418,  415,  413,  412,  411,  409,  408,
      407,  405,  404,  403,  402,  401,  399,  398,  397,  396,
      395,  394,  391,  390,  388,  387,  386,  385,  384,  383,
      381,  380,  379,  378,  377,  376,  374,  373,  372,  371,
      370,  369,  368,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,

      338,  337,  336,  335,  332,  331,  329,  327,  326,  325,
      324,  323,  321,  319,  318,  317,  316,  315,  314,  312,
      311,  310,  309,  308,  307,  305,  304,  303,  302,  300,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  288,
      287,  286,  284,  283,  282,  281,  280,  278,  276,  274,
      273,  271,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  246,  245,  244,  243,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      226,  225,  224,  223,  222,  220,  219,  218,  217,  215,

      214,  213,  212,  211,  210,  209,  207,  206,  204,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  187,
      185,  184,  183,  182,  181,  180,  179,  177,  176,  174,
      173,  171,  170,  168,  167,  166,  165,  164,  163,  162,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  118,  117,  116,
      115,  114,  104,  103,  102,  101,  100,   99,   98,   96,
       95,   94,   93,   91,   90,   89,   88,   85,   83,   79,

       78,   77,   76,   74,   73,   72,   71,   70,   67,   66,
       64,   62,   61,   59,   58,   50,   41,   40,   32,   31,
       29,   28,   26,   18,   11,    9,    8,    7,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../lexer.l"
#define INITIAL 0
/*
 * avrdude - A Downloader/Uploader for AVR device programmers
 * Copyright (C) 2000-2004  Brian S. Dean <bsd@bsdhome.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/* $Id: lexer.l,v 1.33 2005/09/18 20:12:23 joerg_wunsch Exp $ */
#line 23 "../lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>

#include "config.h"
#include "config_gram.h"
#include "lists.h"

extern int    lineno;
extern char * infile;

void pyytext(void);

#define YY_NO_UNPUT

#define str 1

#define incl 2

#define comment 3

#line 738 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 53 "../lexer.l"


#line 892 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 552 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 629 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "../lexer.l"
{ string_buf_ptr = string_buf; BEGIN(str); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "../lexer.l"
{ yylval = hexnumber(yytext); return TKN_NUMBER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "../lexer.l"
{ /* The following eats '#' style comments to end of line */
       BEGIN(comment); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "../lexer.l"
/* eat comments */ 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "../lexer.l"
{ lineno++; BEGIN(INITIAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "../lexer.l"
{  /* The following eats multiline C style comments */
        int c;
        int comment_start;
        
        comment_start = lineno;
        while (1) {
          while (((c = input()) != '*') && (c != EOF)) {
            /* eat up text of comment, but keep counting lines */
            if (c == '\n')
              lineno++;
          }
          
          if (c == '*') {
            while ((c = input()) == '*')
              ;
            if (c == '/')
              break;    /* found the end */
          }
          
          if (c == EOF) {
            fprintf(stderr, "error at %s:%d: EOF in comment\n", 
                    infile, lineno);
            fprintf(stderr, "    comment started on line %d\n", 
                    comment_start);
            exit(1);
            break;
          }
        }
     }
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 103 "../lexer.l"
{ *string_buf_ptr = 0; string_buf_ptr = string_buf; 
         yylval = string(string_buf_ptr); BEGIN(INITIAL); return TKN_STRING; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "../lexer.l"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 106 "../lexer.l"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "../lexer.l"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "../lexer.l"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 109 "../lexer.l"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 110 "../lexer.l"
*(string_buf_ptr++) = yytext[1];
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 111 "../lexer.l"
{ char *yptr = yytext; while (*yptr) 
                                         *(string_buf_ptr++) = *(yptr++); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "../lexer.l"
{ fprintf(stderr, "error at line %d: unterminated character constant\n",
         lineno); 
         exit(1); }
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 118 "../lexer.l"
{ yylval=NULL; return K_ALLOWFULLPAGEBITSTREAM; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 119 "../lexer.l"
{ yylval=NULL; return K_AVR910; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "../lexer.l"
{ yylval=NULL; return K_AVR910_DEVCODE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "../lexer.l"
{ yylval=NULL; return K_PAGE_SIZE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "../lexer.l"
{ yylval=NULL; return K_PAGED; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 123 "../lexer.l"
{ yylval=NULL; return K_BAUDRATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 124 "../lexer.l"
{ yylval=NULL; return K_BS2; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "../lexer.l"
{ yylval=NULL; return K_BUFF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 126 "../lexer.l"
{ yylval=NULL; return K_BUTTERFLY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "../lexer.l"
{ yylval=NULL; return K_CHIP_ERASE_DELAY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "../lexer.l"
{ yylval=NULL; return K_DESC; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 129 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_PARALLEL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 130 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_PROGRAMMER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_SERIAL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "../lexer.l"
{ yylval=NULL; return K_DEVICECODE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 133 "../lexer.l"
{ yylval=NULL; return K_EECR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 134 "../lexer.l"
{ yylval=NULL; return K_EEPROM; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 135 "../lexer.l"
{ yylval=NULL; return K_ENABLEPAGEPROGRAMMING; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "../lexer.l"
{ yylval=NULL; return K_ERRLED; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 137 "../lexer.l"
{ yylval=NULL; return K_FLASH; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 138 "../lexer.l"
{ yylval=NULL; return K_HAS_JTAG; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "../lexer.l"
{ yylval=NULL; return K_ID; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 140 "../lexer.l"
{ yylval=NULL; return K_IDR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 141 "../lexer.l"
{ yylval=NULL; return K_JTAG_MKII; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 142 "../lexer.l"
{ yylval=NULL; return K_MAX_WRITE_DELAY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 143 "../lexer.l"
{ yylval=NULL; return K_MEMORY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 144 "../lexer.l"
{ yylval=NULL; return K_MIN_WRITE_DELAY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "../lexer.l"
{ yylval=NULL; return K_MISO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 146 "../lexer.l"
{ yylval=NULL; return K_MOSI; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 147 "../lexer.l"
{ yylval=NULL; return K_NUM_PAGES; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 148 "../lexer.l"
{ yylval=NULL; return K_NUM_PAGES; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 149 "../lexer.l"
{ yylval=NULL; return K_PAGE_SIZE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 150 "../lexer.l"
{ yylval=NULL; return K_PAGED; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 151 "../lexer.l"
{ yylval=NULL; return K_PAGEL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 152 "../lexer.l"
{ yylval=NULL; return K_PAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 153 "../lexer.l"
{ yylval=NULL; return K_PARALLEL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 154 "../lexer.l"
{ yylval=NULL; return K_PART; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 155 "../lexer.l"
{ yylval=NULL; return K_PGMLED; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 156 "../lexer.l"
{ yylval=NULL; return K_PROGRAMMER; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 157 "../lexer.l"
{ yylval=NULL; return K_PWROFF_AFTER_WRITE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 158 "../lexer.l"
{ yylval=NULL; return K_RAMPZ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 159 "../lexer.l"
{ yylval=NULL; return K_RDYLED; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 160 "../lexer.l"
{ yylval=NULL; return K_READBACK_P1; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "../lexer.l"
{ yylval=NULL; return K_READBACK_P2; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "../lexer.l"
{ yylval=NULL; return K_RETRY_PULSE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "../lexer.l"
{ yylval=NULL; return K_SERBB; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 164 "../lexer.l"
{ yylval=NULL; return K_SERIAL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "../lexer.l"
{ yylval=NULL; return K_SIZE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 166 "../lexer.l"
{ yylval=NULL; return K_SPMCR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 167 "../lexer.l"
{ yylval=NULL; return K_STK500; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "../lexer.l"
{ yylval=NULL; return K_STK500V2; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 169 "../lexer.l"
{ yylval=NULL; return K_STK500_DEVCODE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 170 "../lexer.l"
{ yylval=NULL; return K_TYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "../lexer.l"
{ yylval=NULL; return K_VCC; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 172 "../lexer.l"
{ yylval=NULL; return K_VFYLED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 174 "../lexer.l"
{ yylval=NULL; return K_TIMEOUT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 175 "../lexer.l"
{ yylval=NULL; return K_STABDELAY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 176 "../lexer.l"
{ yylval=NULL; return K_CMDEXEDELAY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 177 "../lexer.l"
{ yylval=NULL; return K_SYNCHLOOPS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 178 "../lexer.l"
{ yylval=NULL; return K_BYTEDELAY; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 179 "../lexer.l"
{ yylval=NULL; return K_POLLVALUE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "../lexer.l"
{ yylval=NULL; return K_POLLINDEX; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 181 "../lexer.l"
{ yylval=NULL; return K_PREDELAY; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 182 "../lexer.l"
{ yylval=NULL; return K_POSTDELAY; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 183 "../lexer.l"
{ yylval=NULL; return K_POLLMETHOD; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 184 "../lexer.l"
{ yylval=NULL; return K_MODE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 185 "../lexer.l"
{ yylval=NULL; return K_DELAY; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 186 "../lexer.l"
{ yylval=NULL; return K_BLOCKSIZE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 187 "../lexer.l"
{ yylval=NULL; return K_READSIZE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 191 "../lexer.l"
{ yylval=new_token(K_DEDICATED); return K_DEDICATED; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 192 "../lexer.l"
{ yylval=new_token(K_IO); return K_IO; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 193 "../lexer.l"
{ yylval=new_token(K_PSEUDO); return K_PSEUDO; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 195 "../lexer.l"
{ yylval=new_token(K_RESET); return K_RESET; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 196 "../lexer.l"
{ yylval=new_token(K_SCK); return K_SCK; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 198 "../lexer.l"
{ yylval=new_token(K_READ); return K_READ; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 199 "../lexer.l"
{ yylval=new_token(K_WRITE); return K_WRITE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 200 "../lexer.l"
{ yylval=new_token(K_READ_LO); return K_READ_LO; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 201 "../lexer.l"
{ yylval=new_token(K_READ_HI); return K_READ_HI; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 202 "../lexer.l"
{ yylval=new_token(K_WRITE_LO); return K_WRITE_LO; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 203 "../lexer.l"
{ yylval=new_token(K_WRITE_HI); return K_WRITE_HI; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 204 "../lexer.l"
{ yylval=new_token(K_LOADPAGE_LO); return K_LOADPAGE_LO; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 205 "../lexer.l"
{ yylval=new_token(K_LOADPAGE_HI); return K_LOADPAGE_HI; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 206 "../lexer.l"
{ yylval=new_token(K_WRITEPAGE); return K_WRITEPAGE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 207 "../lexer.l"
{ yylval=new_token(K_CHIP_ERASE); return K_CHIP_ERASE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 208 "../lexer.l"
{ yylval=new_token(K_PGM_ENABLE); return K_PGM_ENABLE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 210 "../lexer.l"
{ yylval=new_token(K_NO); return K_NO; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 211 "../lexer.l"
{ yylval=new_token(K_YES); return K_YES; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 213 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_COMMA; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 214 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_EQUAL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 215 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_SEMI; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 216 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_TILDE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 218 "../lexer.l"
{ lineno++; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 219 "../lexer.l"
/* ignore whitespace */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 221 "../lexer.l"
{ fprintf(stderr, "error at %s:%d: possible old-style config file entry\n",
             infile, lineno);
     fprintf(stderr, "  Update your config file (see %s%s for a sample)\n",
             CONFIG_DIR, "/avrdude.conf.sample");
     exit(1); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 227 "../lexer.l"
{ fprintf(stderr, "error at %s:%d unrecognized character: \"%s\"\n", 
            infile, lineno, yytext); exit(1); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 230 "../lexer.l"
ECHO;
	YY_BREAK
#line 1585 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 552 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 552 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 551);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 230 "../lexer.l"


