/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_accept[390] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   90,   88,
       86,   85,    4,    6,   88,   82,    3,   88,    1,    1,
       84,   83,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   17,
       18,   10,   89,   89,    7,    8,   86,    0,    3,    1,
        3,    9,    2,    0,    0,    0,    0,    0,   87,    0,
        0,    0,    0,    0,   35,   65,    0,    0,    0,    0,
        0,   80,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
       16,   14,   15,   11,   13,   12,    2,    5,    0,    0,

        0,   22,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       46,    0,    0,    0,    0,    0,    0,    0,    0,   68,
        0,    0,    0,    0,   62,    0,    0,   81,    0,    0,
        0,   23,    0,    0,    0,    0,   25,    0,    0,    0,
        0,    0,    0,    0,    0,   39,   40,    0,    0,    0,
       48,    0,    0,    0,    0,    0,    0,   69,    0,    0,
        0,   57,    0,   61,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   34,    0,    0,
        0,    0,    0,    0,    0,   44,   45,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   67,    0,    0,    0,
        0,   70,   59,    0,   20,    0,    0,    0,    0,    0,
        0,   32,   33,    0,    0,   37,    0,    0,    0,    0,
        0,    0,   49,    0,   66,    0,   52,    0,    0,    0,
        0,   56,   58,   63,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   72,   71,    0,    0,    0,    0,
        0,    0,    0,    0,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   47,    0,    0,    0,
        0,    0,    0,   74,   73,    0,    0,   19,   60,    0,

       64,    0,    0,    0,    0,    0,    0,   41,   42,   43,
        0,    0,    0,    0,    0,    0,   77,    0,   78,    0,
        0,    0,   29,    0,    0,    0,    0,   79,   50,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   76,   75,
        0,    0,    0,   53,   54,   55,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   31,    0,    0,    0,   28,
        0,    0,    0,   30,    0,    0,    0,   36,   38,    0,
       24,   26,    0,    0,    0,    0,   27,   51,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    7,    9,   10,   11,   12,   13,
       14,   14,   15,   14,   14,   14,   16,   17,   18,    1,
       19,    1,    1,    1,   20,   20,   20,   20,   20,   20,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   21,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,
       36,   37,    1,   38,   39,   40,   41,   42,   43,   44,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    3,    1,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    5,
        2,    1,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[397] =
    {   0,
        0,    0,   44,   46,    0,    0,  452,  451,  453,  456,
      450,  456,  456,  456,   44,  456,   43,  445,   53,  406,
      456,  456,  407,   29,   44,  421,   37,  414,   37,  410,
       49,   30,   55,   55,   52,  400,   61,  406,  416,    0,
      456,  456,   67,  456,  456,  456,  440,   81,   97,  397,
      103,  456,  109,    0,  402,   65,  426,   59,  456,  407,
      100,  400,  398,  412,  456,  456,  411,  389,  398,   92,
      392,  456,  396,  100,  395,  392,  400,  388,  380,  107,
      392,  385,  376,  389,  383,  394,  373,  386,  377,    0,
      456,  456,  456,  456,  456,  456,  121,    0,  399,  382,

      387,  456,  384,  371,  373,  378,  385,  382,  375,  367,
      371,  364,  376,  379,  364,  377,  362,  366,  374,  368,
      117,  119,  365,  352,  356,  358,  364,  362,  350,  456,
      356,  359,  370,  357,  456,  350,  342,  456,  369,   74,
      342,  456,  352,  356,  352,  335,  456,  350,  338,  346,
      342,  334,  327,  331,  325,  456,  456,  119,  122,  334,
      456,  339,  338,  326,  337,  334,  334,  127,  320,  314,
      335,  456,  346,  456,  329,  328,  343,  314,  326,  328,
      312,  322,  325,  314,  319,  311,  318,  456,  320,  304,
      296,  302,  316,  315,  298,  456,  456,  303,  300,  308,

      310,  296,  303,  304,  120,  306,  456,  306,  294,  315,
      299,  123,  302,  292,  456,  282,  293,  282,  279,  278,
      292,  456,  456,  287,  284,  456,  283,  278,  283,  280,
      283,  286,  456,  274,  456,  285,  456,  275,  269,  279,
      266,  456,  280,  456,  128,  278,  274,  253,  271,  264,
      273,  268,  272,  257,  265,  251,  250,  257,  261,  241,
      253,  261,  250,  260,  456,  456,  250,  240,  254,  248,
      242,  248,  249,  248,  456,  229,  234,  246,  125,  245,
      248,  242,  241,  228,  227,  238,  456,  231,  236,  234,
      239,  227,  232,  456,  456,  231,  215,  456,  456,  229,

      456,  131,  228,  227,  133,  231,  230,  456,  456,  456,
      224,  212,  209,  211,  208,  204,  456,  220,  222,  205,
      206,  203,  456,  209,  203,  212,  211,  456,  456,  209,
       91,  208,  209,  197,  206,  208,  201,  198,  456,  456,
      201,  200,  188,  456,  456,  456,  189,  198,  196,  189,
      183,  197,  186,  185,  195,  190,  188,  181,  180,  189,
      178,  187,  186,  165,  180,  456,  183,  178,  170,  456,
      158,  157,  163,  456,  155,  166,  154,  456,  456,  137,
      456,  456,  140,  125,  121,   42,  456,  456,  456,  169,
      174,  179,  182,  186,  191,  193

    } ;

static yyconst short int yy_def[397] =
    {   0,
      389,    1,  390,  390,  391,  391,  392,  392,  389,  389,
      389,  389,  389,  389,  393,  389,  389,  389,  393,   19,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  394,
      389,  389,  395,  389,  389,  389,  389,  393,  389,   19,
      389,  389,  389,  396,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  394,
      389,  389,  389,  389,  389,  389,  389,  396,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,    0,  389,
      389,  389,  389,  389,  389,  389

    } ;

static yyconst short int yy_nxt[503] =
    {   0,
       10,   11,   12,   13,   14,   10,   15,   16,   17,   18,
       19,   20,   20,   20,   20,   20,   10,   21,   22,   10,
       10,   10,   23,   24,   25,   26,   27,   28,   10,   10,
       29,   10,   30,   31,   32,   10,   33,   34,   35,   36,
       10,   37,   38,   10,   39,   10,   41,   42,   41,   42,
       48,   56,   49,   51,   51,   51,   51,   51,   51,  389,
       59,   53,   65,   62,   43,   72,   43,   57,  388,   58,
       73,   68,   66,   60,   63,   69,   81,   74,   82,   70,
       79,   80,   83,   75,   71,   86,  103,   48,   87,   49,
       92,   84,   76,   77,   93,  178,   54,   78,  104,  100,

      179,   94,  344,  345,   95,  101,   96,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   97,
       97,   97,   97,   97,   97,  106,  116,  107,  120,  127,
      117,   97,   97,   97,   97,   97,   97,  121,  108,  160,
      162,  109,  193,  195,  245,  128,  129,  196,  205,  238,
      206,  163,  239,  320,  197,  194,  161,  270,  387,  246,
      271,  302,  324,  303,  386,  325,  385,  384,  321,   40,
       40,   40,   40,   40,   44,   44,   44,   44,   44,   45,
       45,   45,   45,   45,   50,   50,   90,  383,   90,   90,
       90,   91,   91,   91,   91,   91,   98,   98,  382,  381,

      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  323,  322,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,

      272,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  244,  243,  242,  241,  240,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      204,  203,  202,  201,  200,  199,  198,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  159,  158,  157,  156,  155,  154,

      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  131,  130,  126,  125,  124,  123,  122,  119,
      118,  115,  114,  113,  112,  111,  110,  105,  102,   99,
      389,   47,   89,   88,   85,   67,   64,   61,   55,  389,
       52,   47,  389,   46,   46,    9,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389
    } ;

static yyconst short int yy_chk[503] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
       15,   24,   15,   17,   17,   17,   17,   17,   17,   19,
       25,   19,   29,   27,    3,   32,    4,   24,  386,   24,
       32,   31,   29,   25,   27,   31,   35,   33,   35,   31,
       34,   34,   35,   33,   31,   37,   58,   48,   37,   48,
       43,   35,   33,   33,   43,  140,   19,   33,   58,   56,

      140,   43,  331,  331,   43,   56,   43,   49,   49,   49,
       49,   49,   49,   51,   51,   51,   51,   51,   51,   53,
       53,   53,   53,   53,   53,   61,   70,   61,   74,   80,
       70,   97,   97,   97,   97,   97,   97,   74,   61,  121,
      122,   61,  158,  159,  212,   80,   80,  159,  168,  205,
      168,  122,  205,  302,  159,  158,  121,  245,  385,  212,
      245,  279,  305,  279,  384,  305,  383,  380,  302,  390,
      390,  390,  390,  390,  391,  391,  391,  391,  391,  392,
      392,  392,  392,  392,  393,  393,  394,  377,  394,  394,
      394,  395,  395,  395,  395,  395,  396,  396,  376,  375,

      373,  372,  371,  369,  368,  367,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  343,  342,  341,  338,  337,
      336,  335,  334,  333,  332,  330,  327,  326,  325,  324,
      322,  321,  320,  319,  318,  316,  315,  314,  313,  312,
      311,  307,  306,  304,  303,  300,  297,  296,  293,  292,
      291,  290,  289,  288,  286,  285,  284,  283,  282,  281,
      280,  278,  277,  276,  274,  273,  272,  271,  270,  269,
      268,  267,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,

      246,  243,  241,  240,  239,  238,  236,  234,  232,  231,
      230,  229,  228,  227,  225,  224,  221,  220,  219,  218,
      217,  216,  214,  213,  211,  210,  209,  208,  206,  204,
      203,  202,  201,  200,  199,  198,  195,  194,  193,  192,
      191,  190,  189,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  173,  171,  170,  169,
      167,  166,  165,  164,  163,  162,  160,  155,  154,  153,
      152,  151,  150,  149,  148,  146,  145,  144,  143,  141,
      139,  137,  136,  134,  133,  132,  131,  129,  128,  127,
      126,  125,  124,  123,  120,  119,  118,  117,  116,  115,

      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  101,  100,   99,   89,   88,   87,   86,   85,
       84,   83,   82,   81,   79,   78,   77,   76,   75,   73,
       71,   69,   68,   67,   64,   63,   62,   60,   57,   55,
       50,   47,   39,   38,   36,   30,   28,   26,   23,   20,
       18,   11,    9,    8,    7,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../lexer.l"
#define INITIAL 0
/*
 * avrdude - A Downloader/Uploader for AVR device programmers
 * Copyright (C) 2000, 2001, 2002, 2003  Brian S. Dean <bsd@bsdhome.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/* $Id: lexer.l,v 1.29 2004/01/03 18:36:44 hinni Exp $ */
#line 23 "../lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>

#include "config.h"
#include "config_gram.h"
#include "lists.h"

extern int    lineno;
extern char * infile;

void pyytext(void);

#define YY_NO_UNPUT

#define str 1

#define incl 2

#define comment 3

#line 649 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 53 "../lexer.l"


#line 803 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 390 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 456 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "../lexer.l"
{ yylval = number(yytext); return TKN_NUMBER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "../lexer.l"
{ string_buf_ptr = string_buf; BEGIN(str); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "../lexer.l"
{ yylval = hexnumber(yytext); return TKN_NUMBER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "../lexer.l"
{ /* The following eats '#' style comments to end of line */
       BEGIN(comment); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "../lexer.l"
/* eat comments */ 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "../lexer.l"
{ lineno++; BEGIN(INITIAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "../lexer.l"
{  /* The following eats multiline C style comments */
        int c;
        int comment_start;
        
        comment_start = lineno;
        while (1) {
          while (((c = input()) != '*') && (c != EOF)) {
            /* eat up text of comment, but keep counting lines */
            if (c == '\n')
              lineno++;
          }
          
          if (c == '*') {
            while ((c = input()) == '*')
              ;
            if (c == '/')
              break;    /* found the end */
          }
          
          if (c == EOF) {
            fprintf(stderr, "error at %s:%d: EOF in comment\n", 
                    infile, lineno);
            fprintf(stderr, "    comment started on line %d\n", 
                    comment_start);
            exit(1);
            break;
          }
        }
     }
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 103 "../lexer.l"
{ *string_buf_ptr = 0; string_buf_ptr = string_buf; 
         yylval = string(string_buf_ptr); BEGIN(INITIAL); return TKN_STRING; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "../lexer.l"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 106 "../lexer.l"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "../lexer.l"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 108 "../lexer.l"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 109 "../lexer.l"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 110 "../lexer.l"
*(string_buf_ptr++) = yytext[1];
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 111 "../lexer.l"
{ char *yptr = yytext; while (*yptr) 
                                         *(string_buf_ptr++) = *(yptr++); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "../lexer.l"
{ fprintf(stderr, "error at line %d: unterminated character constant\n",
         lineno); 
         exit(1); }
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 118 "../lexer.l"
{ yylval=NULL; return K_PAGE_SIZE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 119 "../lexer.l"
{ yylval=NULL; return K_PAGED; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "../lexer.l"
{ yylval=NULL; return K_BAUDRATE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "../lexer.l"
{ yylval=NULL; return K_BS2; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "../lexer.l"
{ yylval=NULL; return K_BUFF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 123 "../lexer.l"
{ yylval=NULL; return K_CHIP_ERASE_DELAY; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 124 "../lexer.l"
{ yylval=NULL; return K_DESC; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_PARALLEL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 126 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_PROGRAMMER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "../lexer.l"
{ yylval=NULL; return K_DEFAULT_SERIAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "../lexer.l"
{ yylval=NULL; return K_DEVICECODE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 129 "../lexer.l"
{ yylval=NULL; return K_STK500_DEVCODE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 130 "../lexer.l"
{ yylval=NULL; return K_AVR910_DEVCODE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "../lexer.l"
{ yylval=NULL; return K_EEPROM; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "../lexer.l"
{ yylval=NULL; return K_ERRLED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 133 "../lexer.l"
{ yylval=NULL; return K_FLASH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 134 "../lexer.l"
{ yylval=NULL; return K_ID; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 135 "../lexer.l"
{ yylval=NULL; return K_MAX_WRITE_DELAY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "../lexer.l"
{ yylval=NULL; return K_MEMORY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 137 "../lexer.l"
{ yylval=NULL; return K_MIN_WRITE_DELAY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 138 "../lexer.l"
{ yylval=NULL; return K_MISO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "../lexer.l"
{ yylval=NULL; return K_MOSI; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 140 "../lexer.l"
{ yylval=NULL; return K_NUM_PAGES; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 141 "../lexer.l"
{ yylval=NULL; return K_NUM_PAGES; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 142 "../lexer.l"
{ yylval=NULL; return K_PAGE_SIZE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 143 "../lexer.l"
{ yylval=NULL; return K_PAGED; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 144 "../lexer.l"
{ yylval=NULL; return K_PAGEL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "../lexer.l"
{ yylval=NULL; return K_PAR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 146 "../lexer.l"
{ yylval=NULL; return K_PARALLEL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 147 "../lexer.l"
{ yylval=NULL; return K_PART; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 148 "../lexer.l"
{ yylval=NULL; return K_PGMLED; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 149 "../lexer.l"
{ yylval=NULL; return K_PROGRAMMER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 150 "../lexer.l"
{ yylval=NULL; return K_PWROFF_AFTER_WRITE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 151 "../lexer.l"
{ yylval=NULL; return K_RDYLED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 152 "../lexer.l"
{ yylval=NULL; return K_READBACK_P1; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 153 "../lexer.l"
{ yylval=NULL; return K_READBACK_P2; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 154 "../lexer.l"
{ yylval=NULL; return K_RETRY_PULSE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 155 "../lexer.l"
{ yylval=NULL; return K_SERIAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 156 "../lexer.l"
{ yylval=NULL; return K_SIZE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 157 "../lexer.l"
{ yylval=NULL; return K_STK500; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 158 "../lexer.l"
{ yylval=NULL; return K_AVR910; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 159 "../lexer.l"
{ yylval=NULL; return K_BUTTERFLY; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 160 "../lexer.l"
{ yylval=NULL; return K_TYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "../lexer.l"
{ yylval=NULL; return K_VCC; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "../lexer.l"
{ yylval=NULL; return K_VFYLED; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "../lexer.l"
{ yylval=new_token(K_DEDICATED); return K_DEDICATED; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "../lexer.l"
{ yylval=new_token(K_IO); return K_IO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "../lexer.l"
{ yylval=new_token(K_PSEUDO); return K_PSEUDO; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 169 "../lexer.l"
{ yylval=new_token(K_RESET); return K_RESET; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 170 "../lexer.l"
{ yylval=new_token(K_SCK); return K_SCK; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 172 "../lexer.l"
{ yylval=new_token(K_READ); return K_READ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 173 "../lexer.l"
{ yylval=new_token(K_WRITE); return K_WRITE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "../lexer.l"
{ yylval=new_token(K_READ_LO); return K_READ_LO; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 175 "../lexer.l"
{ yylval=new_token(K_READ_HI); return K_READ_HI; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 176 "../lexer.l"
{ yylval=new_token(K_WRITE_LO); return K_WRITE_LO; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 177 "../lexer.l"
{ yylval=new_token(K_WRITE_HI); return K_WRITE_HI; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 178 "../lexer.l"
{ yylval=new_token(K_LOADPAGE_LO); return K_LOADPAGE_LO; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 179 "../lexer.l"
{ yylval=new_token(K_LOADPAGE_HI); return K_LOADPAGE_HI; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 180 "../lexer.l"
{ yylval=new_token(K_WRITEPAGE); return K_WRITEPAGE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 181 "../lexer.l"
{ yylval=new_token(K_CHIP_ERASE); return K_CHIP_ERASE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 182 "../lexer.l"
{ yylval=new_token(K_PGM_ENABLE); return K_PGM_ENABLE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 184 "../lexer.l"
{ yylval=new_token(K_NO); return K_NO; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 185 "../lexer.l"
{ yylval=new_token(K_YES); return K_YES; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 187 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_COMMA; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 188 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_EQUAL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 189 "../lexer.l"
{ yylval = NULL; pyytext(); return TKN_SEMI; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 191 "../lexer.l"
{ lineno++; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 192 "../lexer.l"
/* ignore whitespace */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 194 "../lexer.l"
{ fprintf(stderr, "error at %s:%d: possible old-style config file entry\n",
             infile, lineno);
     fprintf(stderr, "  Update your config file (see %s%s for a sample)\n",
             CONFIG_DIR, "/avrdude.conf.sample");
     exit(1); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 200 "../lexer.l"
{ fprintf(stderr, "error at %s:%d unrecognized character: \"%s\"\n", 
            infile, lineno, yytext); exit(1); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 203 "../lexer.l"
ECHO;
	YY_BREAK
#line 1371 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 390 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 390 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 389);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 203 "../lexer.l"


